import type { Asset, AssetType } from "@/types/asset";
import type { Snapshot, SnapshotBreakdown } from "@/types/snapshot";

/**
 * Deterministic demo portfolio for Kerdos.
 *
 * All records carry `isDemo: true` so the Demo Mode exit path (W4) can wipe
 * them in a single indexed query without touching real user data.
 *
 * Price evolution is driven by a seeded PRNG (xmur3 + mulberry32), so
 * `buildDemoPortfolio()` returns byte-identical output on every call.
 * This keeps the landing chart stable across visits and makes W4 visual
 * regression testing trivial.
 *
 * IMPORTANT: This module is DATA-ONLY. It does not touch Dexie, React,
 * or any network / price service. W4 is responsible for `db.assets.bulkPut`
 * and `db.snapshots.bulkPut`.
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Fixed FX rates used by the demo dataset. Values are expressed as
 * "1 unit of CURRENCY = N USD" (i.e. multiply a CURRENCY amount by the
 * rate below to get USD).
 *
 * These are deliberately hard-coded — the demo must render identically
 * offline and must never hit a live FX API. W4 may override if needed.
 */
export const DEMO_FX_TO_USD: Record<string, number> = {
  USD: 1,
  CNY: 1 / 7.2, // ~0.1389
  HKD: 1 / 7.8, // ~0.1282
  JPY: 1 / 150, // ~0.00667
  EUR: 1 / 0.92, // ~1.0870  (1 EUR ≈ 1.087 USD)
};

/** Number of daily snapshots generated by default. */
const DEFAULT_DAYS = 90;

/** Seed string for the PRNG. Changing this reshuffles every demo curve. */
const DEMO_SEED = "kerdos-demo-v1";

/** Reporting base currency for snapshot totals. */
const BASE_CURRENCY = "USD";

/**
 * Asset types that store their own price on the Asset record rather than
 * deriving it from a ticker feed. Kept local to this module to avoid a
 * cross-module import from snapshotService (data layer stays standalone).
 */
const MANUAL_PRICE_TYPES = new Set<AssetType>([
  "real_estate",
  "vehicle",
  "cash",
  "other",
]);

// ---------------------------------------------------------------------------
// Deterministic PRNG (xmur3 + mulberry32)
// ---------------------------------------------------------------------------
//
// xmur3 hashes a string into a 32-bit seed; mulberry32 turns that seed into
// a uniform [0,1) generator. Together they give us ~10 lines of code, no
// dependencies, and fully reproducible randomness — ideal for a demo chart.
//
// Reference: https://stackoverflow.com/a/47593316

function xmur3(str: string): () => number {
  let h = 1779033703 ^ str.length;
  for (let i = 0; i < str.length; i++) {
    h = Math.imul(h ^ str.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return function () {
    h = Math.imul(h ^ (h >>> 16), 2246822507);
    h = Math.imul(h ^ (h >>> 13), 3266489909);
    h ^= h >>> 16;
    return h >>> 0;
  };
}

function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Build a uniform [0,1) generator from a composite seed. */
function makeRng(...parts: (string | number)[]): () => number {
  const key = [DEMO_SEED, ...parts].join("|");
  const seedFn = xmur3(key);
  return mulberry32(seedFn());
}

/**
 * Standard-normal sample via Box-Muller, consuming 2 uniforms per call.
 * Clamps u1 away from zero to avoid log(0) = -Infinity.
 */
function gaussian(rng: () => number): number {
  const u1 = Math.max(rng(), 1e-9);
  const u2 = rng();
  return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
}

// ---------------------------------------------------------------------------
// Date helpers
// ---------------------------------------------------------------------------

function toYMD(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function toCompact(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}${m}${day}`;
}

/** Return a new Date shifted by N whole days (UTC-agnostic, local time). */
function shiftDays(base: Date, offsetDays: number): Date {
  const d = new Date(base);
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + offsetDays);
  return d;
}

function toUSD(amount: number, currency: string): number {
  const rate = DEMO_FX_TO_USD[currency];
  if (rate === undefined) {
    // Unknown currency -> pass through. Should not happen for demo data.
    return amount;
  }
  return amount * rate;
}

// ---------------------------------------------------------------------------
// Portfolio definition
// ---------------------------------------------------------------------------

/**
 * Per-asset spec used to seed both the Asset record and the price walker.
 * `startPrice` is a rough approximation of the ticker's price ~90 days
 * before "today" (calendar ~Jan 2026 at time of writing). Values are
 * intentionally approximate — this is a demo, not a historical replay.
 */
interface AssetSpec {
  id: string;
  name: string;
  type: AssetType;
  ticker?: string;
  quantity: number;
  costPrice?: number;
  costCurrency: string;
  /** Currency the ticker / manualPrice is quoted in. */
  priceCurrency: string;
  /** Starting unit price 90 days ago (approximate). */
  startPrice: number;
  /** Manual-price path (real estate / cash / etc). */
  manualPrice?: number;
  /** Daily drift (mean log-return). */
  drift: number;
  /** Daily volatility (stdev of log-return). */
  vol: number;
  subType?: string;
  region?: string;
  notes?: string;
}

/**
 * 20-asset mid-career urban professional portfolio.
 *
 * Start prices are approximate references for Jan 2026 and are NOT guaranteed
 * to match real historical quotes. They give the demo a plausible starting
 * point; day-over-day movement is driven by the PRNG below.
 */
const ASSET_SPECS: AssetSpec[] = [
  // --- US stocks (5) ---
  {
    id: "demo-aapl",
    name: "Apple Inc.",
    type: "us_stock",
    ticker: "AAPL",
    quantity: 50,
    costPrice: 150,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 185,
    drift: 0.0003,
    vol: 0.012,
    subType: "Tech",
    region: "US",
  },
  {
    id: "demo-msft",
    name: "Microsoft Corporation",
    type: "us_stock",
    ticker: "MSFT",
    quantity: 30,
    costPrice: 320,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 420,
    drift: 0.0003,
    vol: 0.012,
    subType: "Tech",
    region: "US",
  },
  {
    id: "demo-nvda",
    name: "NVIDIA Corporation",
    type: "us_stock",
    ticker: "NVDA",
    quantity: 20,
    costPrice: 450,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 900,
    drift: 0.0003,
    vol: 0.02, // NVDA is demonstrably more volatile than mega-cap peers
    subType: "Tech",
    region: "US",
  },
  {
    id: "demo-googl",
    name: "Alphabet Inc. Class A",
    type: "us_stock",
    ticker: "GOOGL",
    quantity: 15,
    costPrice: 130,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 175,
    drift: 0.0003,
    vol: 0.012,
    subType: "Tech",
    region: "US",
  },
  {
    id: "demo-brk-b",
    name: "Berkshire Hathaway Inc. Class B",
    type: "us_stock",
    ticker: "BRK.B",
    quantity: 10,
    costPrice: 320,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 440,
    drift: 0.00025,
    vol: 0.009, // lower vol, diversified holdco
    subType: "Financials",
    region: "US",
  },

  // --- A-shares (3) ---
  {
    id: "demo-600519",
    name: "\u8d35\u5dde\u8305\u53f0", // 贵州茅台
    type: "cn_stock",
    ticker: "600519.SS",
    quantity: 5,
    costPrice: 1600,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 1650,
    drift: 0.0002,
    vol: 0.014,
    subType: "Consumer",
    region: "CN",
  },
  {
    id: "demo-000858",
    name: "\u4e94\u7cae\u6db2", // 五粮液
    type: "cn_stock",
    ticker: "000858.SZ",
    quantity: 50,
    costPrice: 180,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 155,
    drift: 0.0002,
    vol: 0.015,
    subType: "Consumer",
    region: "CN",
  },
  {
    id: "demo-300750",
    name: "\u5b81\u5fb7\u65f6\u4ee3", // 宁德时代
    type: "cn_stock",
    ticker: "300750.SZ",
    quantity: 20,
    costPrice: 200,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 210,
    drift: 0.0003,
    vol: 0.02,
    subType: "New Energy",
    region: "CN",
  },

  // --- Crypto (2) ---
  {
    id: "demo-btc",
    name: "Bitcoin",
    type: "crypto",
    ticker: "BTC",
    quantity: 0.15,
    costPrice: 42000,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 65000,
    drift: 0.0005,
    vol: 0.04,
    subType: "Crypto",
    region: "Global",
  },
  {
    id: "demo-eth",
    name: "Ethereum",
    type: "crypto",
    ticker: "ETH",
    quantity: 2,
    costPrice: 2400,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 3400,
    drift: 0.0005,
    vol: 0.045,
    subType: "Crypto",
    region: "Global",
  },

  // --- Cash / FX (5) ---
  // For cash we model the asset as quantity = amount held in that currency,
  // with manualPrice = 1 (face value). Price "drift" here represents tiny
  // FX fluctuation relative to USD — it is not actually applied to the
  // manualPrice (which stays 1); we instead vary the FX-to-USD conversion
  // path inside the snapshot generator. Keeping drift/vol here for symmetry.
  {
    id: "demo-cash-cny",
    name: "\u4eba\u6c11\u5e01\u73b0\u91d1", // 人民币现金
    type: "cash",
    quantity: 80000,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 1,
    manualPrice: 1,
    drift: 0,
    vol: 0.003,
    region: "CN",
  },
  {
    id: "demo-cash-usd",
    name: "US Dollar Cash",
    type: "cash",
    quantity: 5000,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 1,
    manualPrice: 1,
    drift: 0,
    vol: 0, // base currency — no FX noise
    region: "US",
  },
  {
    id: "demo-cash-hkd",
    name: "Hong Kong Dollar Cash",
    type: "cash",
    quantity: 10000,
    costCurrency: "HKD",
    priceCurrency: "HKD",
    startPrice: 1,
    manualPrice: 1,
    drift: 0,
    vol: 0.003,
    region: "HK",
  },
  {
    id: "demo-cash-jpy",
    name: "Japanese Yen Cash",
    type: "cash",
    quantity: 200000,
    costCurrency: "JPY",
    priceCurrency: "JPY",
    startPrice: 1,
    manualPrice: 1,
    drift: 0,
    vol: 0.003,
    region: "JP",
  },
  {
    id: "demo-cash-eur",
    name: "Euro Cash",
    type: "cash",
    quantity: 1000,
    costCurrency: "EUR",
    priceCurrency: "EUR",
    startPrice: 1,
    manualPrice: 1,
    drift: 0,
    vol: 0.003,
    region: "EU",
  },

  // --- Real estate (2) ---
  {
    id: "demo-re-cn",
    name: "\u4e00\u7ebf\u57ce\u5e02\u4e3b\u529b\u6237\u578b", // 一线城市主力户型
    type: "real_estate",
    quantity: 1,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 2800000,
    manualPrice: 2800000,
    drift: 0.0001, // slow appreciation
    vol: 0.0005, // real estate shouldn't visibly jitter daily
    region: "CN",
    notes: "Demo: first-tier city primary residence",
  },
  {
    id: "demo-re-us",
    name: "Overseas Vacation Home",
    type: "real_estate",
    quantity: 1,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 180000,
    manualPrice: 180000,
    drift: 0.0001,
    vol: 0.0005,
    region: "US",
    notes: "Demo: small vacation property",
  },

  // --- Other: gold + ETFs (3) ---
  {
    id: "demo-xauusd",
    name: "Gold (Ounce)",
    type: "gold",
    ticker: "XAUUSD",
    quantity: 20,
    costPrice: 1900,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 2050,
    drift: 0.00025,
    vol: 0.01,
    subType: "Precious Metal",
    region: "Global",
  },
  {
    id: "demo-510300",
    name: "\u6caa\u6df1 300 ETF", // 沪深 300 ETF
    type: "etf",
    ticker: "510300.SS",
    quantity: 1000,
    costPrice: 4.2,
    costCurrency: "CNY",
    priceCurrency: "CNY",
    startPrice: 3.85,
    drift: 0.0003,
    vol: 0.011,
    subType: "Broad Index",
    region: "CN",
  },
  {
    id: "demo-spy",
    name: "SPDR S&P 500 ETF Trust",
    type: "etf",
    ticker: "SPY",
    quantity: 20,
    costPrice: 420,
    costCurrency: "USD",
    priceCurrency: "USD",
    startPrice: 560,
    drift: 0.0003,
    vol: 0.009,
    subType: "Broad Index",
    region: "US",
  },
];

// ---------------------------------------------------------------------------
// Market events
// ---------------------------------------------------------------------------
//
// Two scripted events give the 90-day curve a "story": a mid-period pullback
// and a late-period rebound. Each event injects a fixed daily shock on top
// of the PRNG walk for the affected asset classes.

interface EventWindow {
  startDay: number; // inclusive
  endDay: number; // inclusive
  /** Daily shock per type bucket (applied to log-return additively). */
  shockByBucket: Partial<Record<"stock" | "crypto" | "etf" | "gold", number>>;
}

const EVENTS: EventWindow[] = [
  // Pullback: days 40..45 (6 trading days)
  // Stocks -5% to -8% total → per-day ≈ -1.1%  (6 days × -1.1% ≈ -6.4%)
  // Crypto -15% total       → per-day ≈ -2.7%
  {
    startDay: 40,
    endDay: 45,
    shockByBucket: {
      stock: -0.011,
      etf: -0.011,
      crypto: -0.027,
      gold: 0.004, // mild safe-haven bid
    },
  },
  // Rebound: days 75..78 (4 trading days)
  // Stocks +4% total → per-day ≈ +1.0%
  // Crypto +10% total → per-day ≈ +2.4%
  {
    startDay: 75,
    endDay: 78,
    shockByBucket: {
      stock: 0.01,
      etf: 0.01,
      crypto: 0.024,
    },
  },
];

function bucketOf(
  type: AssetType,
): "stock" | "crypto" | "etf" | "gold" | "other" {
  if (type === "us_stock" || type === "cn_stock") return "stock";
  if (type === "etf") return "etf";
  if (type === "crypto") return "crypto";
  if (type === "gold") return "gold";
  return "other";
}

function eventShock(type: AssetType, day: number): number {
  const b = bucketOf(type);
  let total = 0;
  for (const ev of EVENTS) {
    if (day < ev.startDay || day > ev.endDay) continue;
    if (b === "other") continue;
    const s = ev.shockByBucket[b];
    if (s !== undefined) total += s;
  }
  return total;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build 20 demo Asset records. All rows are tagged `isDemo: true` and share
 * the same creation timestamp (the start of the 90-day window) so the demo
 * chart includes them from day 0.
 */
export function generateDemoAssets(): Asset[] {
  const start = shiftDays(new Date(), -(DEFAULT_DAYS - 1));
  const ts = start; // same Date instance for createdAt/updatedAt

  return ASSET_SPECS.map((spec): Asset => {
    const base: Asset = {
      id: spec.id,
      name: spec.name,
      type: spec.type,
      quantity: spec.quantity,
      costCurrency: spec.costCurrency,
      createdAt: ts,
      updatedAt: ts,
      isDemo: true,
    };
    if (spec.ticker !== undefined) base.ticker = spec.ticker;
    if (spec.costPrice !== undefined) base.costPrice = spec.costPrice;
    if (spec.manualPrice !== undefined) {
      base.manualPrice = spec.manualPrice;
      base.manualPriceUpdatedAt = ts;
    }
    if (spec.notes !== undefined) base.notes = spec.notes;
    if (spec.subType !== undefined) base.subType = spec.subType;
    if (spec.region !== undefined) base.region = spec.region;
    return base;
  });
}

/**
 * Generate `days` daily end-of-day snapshots. Prices walk forward from each
 * asset's `startPrice` using a seeded geometric random walk; two scripted
 * market events are layered on top. Values are summed into USD using the
 * fixed FX table above.
 */
export function generateDemoSnapshots(
  assets: Asset[],
  days: number = DEFAULT_DAYS,
): Snapshot[] {
  if (days <= 0) return [];

  // Build a quick lookup from assetId → spec so we can replay the price walk.
  const specById = new Map<string, AssetSpec>();
  for (const s of ASSET_SPECS) specById.set(s.id, s);

  // Precompute the per-day unit price for every asset. We evolve prices
  // with a log-return random walk so they can't go negative.
  //   price[d] = price[d-1] * exp(drift + vol*gaussian + event_shock)
  // Manual-price assets (real estate / cash) still evolve so the demo has
  // believable total-networth movement, but with tiny vol.
  const pricesByAsset: Record<string, number[]> = {};
  for (const spec of ASSET_SPECS) {
    const rng = makeRng("price", spec.id);
    const series: number[] = new Array(days);
    let p = spec.startPrice;
    series[0] = p;
    for (let d = 1; d < days; d++) {
      const shock = gaussian(rng);
      const ev = eventShock(spec.type, d);
      const logRet = spec.drift + spec.vol * shock + ev;
      p = p * Math.exp(logRet);
      series[d] = p;
    }
    pricesByAsset[spec.id] = series;
  }

  // FX noise: for cash assets we let the effective USD value wobble slightly
  // via a per-currency, per-day multiplier. Hard-coded currencies stay
  // deterministic by seeding on the currency code.
  const fxWalk: Record<string, number[]> = {};
  for (const cur of Object.keys(DEMO_FX_TO_USD)) {
    const rng = makeRng("fx", cur);
    const arr: number[] = new Array(days);
    let m = 1;
    arr[0] = m;
    for (let d = 1; d < days; d++) {
      const sigma = cur === "USD" ? 0 : 0.003;
      m = m * Math.exp(sigma * gaussian(rng));
      arr[d] = m;
    }
    fxWalk[cur] = arr;
  }

  // Only include assets we actually have specs for. (Defensive — caller
  // normally passes the output of generateDemoAssets.)
  const activeAssets = assets.filter((a) => specById.has(a.id));

  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const snapshots: Snapshot[] = new Array(days);

  for (let d = 0; d < days; d++) {
    const date = shiftDays(today, -(days - 1 - d));
    const dateStr = toYMD(date);
    const breakdown: SnapshotBreakdown[] = [];
    let total = 0;

    for (const asset of activeAssets) {
      const spec = specById.get(asset.id)!;
      const isManual = MANUAL_PRICE_TYPES.has(spec.type);

      // Unit price in the asset's quoted currency.
      let unitPrice: number;
      if (isManual && spec.manualPrice !== undefined) {
        // Manual-price assets (real estate / cash / other) use the walked
        // series anchored at manualPrice, so real estate still appreciates
        // slowly and cash stays at ~1.
        const walked = pricesByAsset[spec.id][d];
        unitPrice = walked;
      } else {
        unitPrice = pricesByAsset[spec.id][d];
      }

      const rawValue = unitPrice * asset.quantity;

      // Convert quoted currency → USD, adding a tiny FX wobble per day.
      const fxMult = fxWalk[spec.priceCurrency]?.[d] ?? 1;
      const valueUSD = toUSD(rawValue, spec.priceCurrency) * fxMult;

      breakdown.push({
        assetId: asset.id,
        value: valueUSD,
        price: unitPrice,
      });
      total += valueUSD;
    }

    snapshots[d] = {
      id: `demo-snap-${toCompact(date)}`,
      date: dateStr,
      totalNetWorth: total,
      currency: BASE_CURRENCY,
      breakdown,
      createdAt: new Date(date.getFullYear(), date.getMonth(), date.getDate()),
      intraday: false,
    };
  }

  return snapshots;
}

/**
 * One-shot helper for W4: returns the 20 demo assets plus `days` daily
 * snapshots, both ready for `db.assets.bulkPut` / `db.snapshots.bulkPut`.
 */
export function buildDemoPortfolio(days: number = DEFAULT_DAYS): {
  assets: Asset[];
  snapshots: Snapshot[];
} {
  const assets = generateDemoAssets();
  const snapshots = generateDemoSnapshots(assets, days);
  return { assets, snapshots };
}
